#ifndef PROTOCOL_H
#define PROTOCOL_H

/**STRUCTURES 0 - 9**/
#define LOGIN_TO_LOBBY_REQUEST 4

#define NEW_SESSION_REQUEST 5
#define NEW_SESSION_RESPONSE 5

#define NEW_GAME_REQUEST 6
#define NEW_GAME_RESPONSE 6

/**CLIENT INFO 10 - 20**/
#define CLIENTS_ID_RESPONSE 10

#define CLIENTS_NAME_REQUEST 11
#define CLIENTS_NAME_RESPONSE 11

#define NUMBER_OF_CLIENTS_ONLINE_REQUEST 12
#define NUMBER_OF_CLIENTS_ONLINE_RESPONSE 12

#define SESSION_ID_REQUEST 13
#define SESSION_ID_RESPONSE 13

#define IS_ALIVE_REQUEST 14
#define IS_ALIVE_RESPONSE 14

#define STATUS_RESPONSE 15
/**ACTIONS 20 - 30**/

#define RETURN_TO_LOBBY_RESPONSE 20

#define RECONNECT_REQUEST 21
#define RECONNECT_RESPONE 21

#define DISCONNECT_REQUEST 22

/**GAME 30 - 40**/

#define WANT_TO_PLAY_GAME_RESPONSE 30

#define NEW_GAME_BEGIN_RESPONSE 31

#define NUMBER_OF_PEXESOS_RESPONSE 32

#define OPPONENTS_NAME_RESPONSE 33

#define IS_PLAYER_TURN_RESPONSE 34

#define PEXESO_REVEALED_REQUEST 35
#define PEXESO_REVEAL_RESPONSE 35

#define PEXESO_REVEAL_ID_RESPONSE 36

#define SUCCESFULLY_REVEALED_PEXESO_RESPONSE 37

#define SCORE_RESPONSE 38

#define END_OF_GAME 39

#define PLAY_AGAIN_RESPONSE 40

/**ERRORS 90 - 99**/
#define OPPONENT_LEFT_RESPONSE 94
#define OPPONENT_LEFT_COMPLETELY_RESPONSE 95
#define NOT_VALID_MESSAGE 90
#define NOT_LOGGED_IN_LOBBY 91
#define ALREADY_LOGGED_IN 92
#define ALREADY_IN_SESSION 93

#endif

