#ifndef PROTOCOL_H
#define PROTOCOL_H

/**LOBBY HANDLE**/
#define LOGIN_TO_LOBBY_REQUEST 4
    #define CLIENTS_ID_RESPONSE 10
/**SESSION HANDLE**/
#define NEW_SESSION_REQUEST 5
#define NEW_SESSION_RESPONSE 5
/**GAME HANDLE**/
#define NEW_GAME_REQUEST 6
#define NEW_GAME_RESPONSE 6
    #define NEW_GAME_BEGIN_RESPONSE 13
    #define WANT_TO_PLAY_GAME_RESPONSE 14
    #define PEXESO_REVEALED_REQUEST 20
    #define PEXESO_REVEAL_RESPONSE 20
    #define PEXESO_REVEAL_ID_RESPONSE 24
    #define IS_PLAYER_TURN_RESPONSE 21
    #define PLAY_AGAIN_RESPONSE 25
    #define SCORE_RESPONSE 22
    #define SUCCESFULLY_REVEALED_PEXESO_RESPONSE 23
    #define END_OF_GAME 27
    #define OPPONENTS_NAME_RESPONSE 28
    #define OPPONENT_LEFT_RESPONSE 56

#define SESSION_ID_REQUEST 40
#define SESSION_ID_RESPONSE 40

#define CLIENTS_NAME_REQUEST 41
#define CLIENTS_NAME_RESPONSE 41

#define STATUS_RESPONSE 42

#define NUMBER_OF_CLIENTS_ONLINE_REQUEST 43
#define NUMBER_OF_CLIENTS_ONLINE_RESPONSE 43

#define RETURN_TO_LOBBY_RESPONSE 44

#define IS_ALIVE_REQUEST 45
#define IS_ALIVE_RESPONSE 45

#define RECONNECT_REQUEST 46
#define RECONNECT_RESPONE 46

#define NUMBER_OF_PEXESOS_RESPONSE 47

#define OPPONENT_LEFT_COMPLETELY_RESPONSE 48

#define DISCONNECT_REQUEST 49

#define NOT_VALID_MESSAGE 90

#define SESSION_RESPONSE 70
#define LOGGED_IN_LOBBY 60

#define NOT_LOGGED_IN_LOBBY 91
#define ALREADY_LOGGED_IN 92
#define ALREADY_IN_SESSION 93

#define LOGGED_OUT_TIMEOUT 60
/*
#define NEXT_TURN 20
// Hrac skoroval
#define PLAYER_SCORED 40
// Hrac neskoroval
#define PLAYER_NOT_SCORED 41
// Hrac odhalil pexeso
#define PLAYER_REVEALED_PEXESO 42
// Index pexesa je spatny
#define INVALID_PEXESO_REVEAL 91
// Odhaleni pexesa, ktera uz je odhalena
#define REVEALED_PEXESO_REVEAL 92
// Konec hry
#define GAME_OVER 100
*/


#endif

